### PR TITLE
Feat/close dbs on timeout

### PR DESCRIPTION
**Pull request by oed**
This PR makes the pinning logic close the stores after a timeout of 30 minutes. Note that this might break the case where a user has their 3box-js instance open for over 30 minutes and then makes a write. However this will be fixed in https://github.com/3box/3box-js/issues/231

This PR should be reviewed and merged after #37 has been merged

### CODE REVIEW

**Comment by michaelsena** [comment]
@oed I’m worried about this. I often log in and leave my window open and then edit profile maybe an hour later. This would break, correct?

**Comment by oed** [comment]
@michaelsena yeah, that's correct. Same thing would happen if the server was restarted for some reason. 
We can hold of with actually merging this before https://github.com/3box/3box-js/issues/231 has been implemented!

**Comment by zachferland** [comment]
@oed want to also move this PR onto develop? instead of master

**Comment by oed** [comment]
@zachferland yes please!

**Comment by oed** [comment]
Yeah that makes sense @zachferland I'll create a story for making it more efficient!
Rebasing and merging this.

**Comment by oed** [comment]
Actually I'll wait with merging this until we have made a release of 3box@1.2.0!

**Comment by oed** [comment]
The code in this will make it easier to solve the issues with multiple entries of the same store in the rootStore. Merging this now and basing the bugfix on it!

**Pull request merged**
