### PR TITLE
fix: Remove profile api/cache code/module from the pinning server 

### LINKED ISSUE #81: Remove profile api/cache code/module from the pinning server
Being moved to separate repo/service

### PR DESCRIPTION
**Pull request by lsenta**
fix #81.

### CODE REVIEW

**Comment by oed** [comment]
Looks good, only some linting problem to fix.
Also I don't think we'll merge this yet for a while 🙂

**Comment by lsenta** [comment]
I `npm rm` the modules that where not used and `npm prune` to make sure there are no unused modules, not sure if that's enough to get rid of the useless dependencies of dependencies.

**Comment by oed** [comment]
Yeah, I think that's fine @lsenta

**Comment by zachferland** [comment]
Yeah going to create a medium term branch for all scaling/reliability stories that we can both merge our PRs into. Will keep in separate branch from develop until release dates become more known.

**Pull request merged**
